repository:
  name: ai-on-the-edge-backend
  description: A training project for creating a backend system and CI/CD.
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: develop
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system 🐛.

  - name: feature
    color: '#336699'
    description: New functionality.

  - name: dependencies
    color: '#b4a8d1'
    description: Issue related to dependencies.

  - name: documentation
    color: '#0052cc'
    description: Creating docs.

  - name: refactoring
    color: '#fbca04'
    description: Changes in the way the code works internally without changing the output produced. Contrast to "cleanup".

  - name: techdept
    color: '#ff7619'
    description: Changes that remove or significantly update old unused code and/or dependencies.

  - name: CI/CD
    color: '#5319e7'
    description: Everything which related to CI/CD.

collaborators:
  - username: peterpal00
    permission: admin

branches:
  - name: develop, production

    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        push_restrictions:
          users_url:
            - "!*"
          teams_url:
            - "!*"
      allow_deletions: false
      allow_force_pushes: false