name: Lint check

on:
  push:
    branches:
      - develop

jobs:
  lint-check:
    name: Lint checking
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install poetry
      run: pip install poetry==1.2.2

    - name: Install dependencies
      run: make install

    - name: Lint check
      run: make lint
