name: Apply Terraform

on:
  push:
    branches:
      - develop

jobs:
  apply:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      id: plan
      run: terraform plan -out=tfplan -detailed-exitcode

    - name: Apply Terraform Plan
      if: steps.plan.outputs.exit_code == 2
      run: terraform apply tfplan